//SECURITY//
export const SET_CSRF_TOKEN = "SET_CSRF_TOKEN";

//LOGIN//
export const AUTH_LOGIN  = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_ERROR  = "AUTH_ERROR";

//MENU//
export const MENU_SHOW  = "MENU_SHOW";

//ARTICLES//
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_ARTICLES_VALIDATE = "FETCH_ARTICLES_VALIDATE";
export const FETCH_ARTICLES_ERROR = "FETCH_ARTICLES_ERROR";
export const SORT_ARTICLES = "SORT_ARTICLES";
export const DELETE_ARTICLE_VALIDATE = "DELETE_ARTICLE_VALIDATE";

//ARTICLE//
export const SET_ARTICLE_TITLE = "SET_ARTICLE_TITLE";
export const SET_ARTICLE_CATEGORIE = "SET_ARTICLE_CATEGORIE";
export const SET_ARTICLE_VIGNETTE = "SET_ARTICLE_VIGNETTE";
export const ADD_ARTICLE_PARAGRAPH = "ADD_ARTICLE_PARAGRAPH";
export const ADD_ARTICLE_IMAGE = "ADD_ARTICLE_IMAGE";
export const SET_ARTICLE_IMAGES = "SET_ARTICLE_IMAGES";
export const DELETE_ARTICLE_ITEM = "DELETE_ARTICLE_ITEM";
export const SORT_ARTICLE_CONTENT = "SORT_ARTICLE_CONTENT";
export const SET_ARTICLE_CONTENT = "SET_ARTICLE_CONTENT";
export const SET_ARTICLE_CONTENT_SELECTED = "SET_ARTICLE_CONTENT_SELECTED";
export const SET_ARTICLE_VALIDATE = "SET_ARTICLE_VALIDATE";
export const SET_ARTICLE_PUBLISHED = "SET_ARTICLE_PUBLISHED";
export const SET_ARTICLE = "SET_ARTICLE";

//COMMENTS//
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_VALIDATE = "FETCH_COMMENTS_VALIDATE";
export const FETCH_COMMENTS_ERROR = "FETCH_COMMENTS_ERROR";
export const SORT_COMMENTS = "SORT_COMMENTS";
export const SHOWALL_COMMENTS = "SHOWALL_COMMENTS";
export const DELETE_COMMENTS_VALIDATE = "DELETE_COMMENTS_VALIDATE";
export const SET_COMMENTS_CONTENT = "SET_COMMENTS_CONTENT";

//COMMENT//
export const FETCH_COMMENT = "FETCH_COMMENT";
export const FETCH_COMMENT_VALIDATE = "FETCH_COMMENT_VALIDATE";
export const FETCH_COMMENT_ERROR = "FETCH_COMMENT_ERROR";

//ANSWER//
export const INIT_ANSWER = "INIT_ANSWER";
export const SET_ANSWER_CONTENT = "SET_ANSWER_CONTENT";
export const SET_ANSWER_VALIDATE = "SET_ANSWER_VALIDATE";

//SEARCH//
export const SET_SEARCH_CONTENT = "SET_SEARCH_CONTENT";
export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";
export const SET_SEARCH_FILTERS = "SET_SEARCH_FILTERS";

//POPUP//
export const SHOW_POPUP = "SHOW_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";