//SECURITY//
export const SET_CSRF_TOKEN = "SET_CSRF_TOKEN";

//LOGIN//
export const AUTH_LOGIN  = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_ERROR  = "AUTH_ERROR";

//MENU//
export const MENU_SHOW  = "MENU_SHOW";

//ARTICLES//
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_ARTICLES_VALIDATE = "FETCH_ARTICLES_VALIDATE";
export const FETCH_ARTICLES_ERROR = "FETCH_ARTICLES_ERROR";
export const SORT_ARTICLES = "SORT_ARTICLES";

//COMMENTS//
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_VALIDATE = "FETCH_COMMENTS_VALIDATE";
export const FETCH_COMMENTS_ERROR = "FETCH_COMMENTS_ERROR";
export const SORT_COMMENTS = "SORT_COMMENTS";

//COMMENT//
export const FETCH_COMMENT = "FETCH_COMMENT";
export const FETCH_COMMENT_VALIDATE = "FETCH_COMMENT_VALIDATE";
export const FETCH_COMMENT_ERROR = "FETCH_COMMENT_ERROR";