//MENU//
export const SET_MENU_OPEN = "SET_MENU_OPEN";
//ARTICLES//
export const SET_ARTICLES_CONTENT = "SET_ARTICLES_CONTENT";
export const ADD_ARTICLES_SHOW = "ADD_ARTICLES_SHOW";
//ARTICLE//
export const SET_ARTICLE = "SET_ARTICLE";
//COMMENTS//
export const SET_COMMENTS = "SET_COMMENTS";
//FILTER//
export const SET_FILTER_CATEGORIE = "SET_FILTER_CATEGORIE";